services:

  proxy:
    container_name: proxy
    build:
      context: ../proxy/development
    ports:
      - "80:80"
    depends_on:
      - client
      - tabs-api

  client:
    container_name: client
    build:
      context: ../client
    ports:
      - "3000:3000"

  tabs-api:
    container_name: tabs-api
    build:
      context: ../tabs-api
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:18
    volumes:
      - /var/lib/postgresql
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=guitartabsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db

  worker:
    build:
      context: ../tabs-api
    command: celery -A app.celery.task_queue.celery_task_queue worker --loglevel=info
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  db_data: